### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by ThePrez** [AndyYouens/f_Weather#3]
```
    error: Error: cannot POST /data/2.5/weather?q=London%2Cuk&appid=%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A&units=metric (401)
        at Response.toError (/home/JGORZINS/projects/f_Weather/node_modules/superagent/lib/node/response.js:98:13)
        at ResponseBase._setStatusProperties (/home/JGORZINS/projects/f_Weather/node_modules/superagent/lib/response-base.js:119:48)
        at new Response (/home/JGORZINS/projects/f_Weather/node_modules/superagent/lib/node/response.js:44:8)
        at Request._emitResponse (/home/JGORZINS/projects/f_Weather/node_modules/superagent/lib/node/index.js:930:18)
        at /home/JGORZINS/projects/f_Weather/node_modules/superagent/lib/node/index.js:1127:42
        at IncomingMessage.<anonymous> (/home/JGORZINS/projects/f_Weather/node_modules/superagent/lib/node/parsers/json.js:22:7)
        at IncomingMessage.emit (node:events:406:35)
        at endReadableNT (node:internal/streams/readable:1329:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      status: 401,
      text: '{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}',
      method: 'POST',
      path: '/data/2.5/weather?q=London%2Cuk&appid=%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A%2A&units=metric'
    },
```

**Comment by AndyYouens** [comment]
Expertly done!
